// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc2
// source: services/post.proto

package pbobjs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostExt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	Exts          []*PostExtItem         `protobuf:"bytes,2,rep,name=exts,proto3" json:"exts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostExt) Reset() {
	*x = PostExt{}
	mi := &file_services_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostExt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostExt) ProtoMessage() {}

func (x *PostExt) ProtoReflect() protoreflect.Message {
	mi := &file_services_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostExt.ProtoReflect.Descriptor instead.
func (*PostExt) Descriptor() ([]byte, []int) {
	return file_services_post_proto_rawDescGZIP(), []int{0}
}

func (x *PostExt) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PostExt) GetExts() []*PostExtItem {
	if x != nil {
		return x.Exts
	}
	return nil
}

type PostExtItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserInfo      *UserInfo              `protobuf:"bytes,4,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostExtItem) Reset() {
	*x = PostExtItem{}
	mi := &file_services_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostExtItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostExtItem) ProtoMessage() {}

func (x *PostExtItem) ProtoReflect() protoreflect.Message {
	mi := &file_services_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostExtItem.ProtoReflect.Descriptor instead.
func (*PostExtItem) Descriptor() ([]byte, []int) {
	return file_services_post_proto_rawDescGZIP(), []int{1}
}

func (x *PostExtItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PostExtItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PostExtItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PostExtItem) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	UserPortrait  string                 `protobuf:"bytes,3,opt,name=userPortrait,proto3" json:"userPortrait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_services_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_services_post_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetUserPortrait() string {
	if x != nil {
		return x.UserPortrait
	}
	return ""
}

var File_services_post_proto protoreflect.FileDescriptor

const file_services_post_proto_rawDesc = "" +
	"\n" +
	"\x13services/post.proto\"C\n" +
	"\aPostExt\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\x12 \n" +
	"\x04exts\x18\x02 \x03(\v2\f.PostExtItemR\x04exts\"z\n" +
	"\vPostExtItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12%\n" +
	"\buserInfo\x18\x04 \x01(\v2\t.UserInfoR\buserInfo\"b\n" +
	"\bUserInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\"\n" +
	"\fuserPortrait\x18\x03 \x01(\tR\fuserPortraitB\x11Z\x0fservices/pbobjsb\x06proto3"

var (
	file_services_post_proto_rawDescOnce sync.Once
	file_services_post_proto_rawDescData []byte
)

func file_services_post_proto_rawDescGZIP() []byte {
	file_services_post_proto_rawDescOnce.Do(func() {
		file_services_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_post_proto_rawDesc), len(file_services_post_proto_rawDesc)))
	})
	return file_services_post_proto_rawDescData
}

var file_services_post_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_post_proto_goTypes = []any{
	(*PostExt)(nil),     // 0: PostExt
	(*PostExtItem)(nil), // 1: PostExtItem
	(*UserInfo)(nil),    // 2: UserInfo
}
var file_services_post_proto_depIdxs = []int32{
	1, // 0: PostExt.exts:type_name -> PostExtItem
	2, // 1: PostExtItem.userInfo:type_name -> UserInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_post_proto_init() }
func file_services_post_proto_init() {
	if File_services_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_post_proto_rawDesc), len(file_services_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_post_proto_goTypes,
		DependencyIndexes: file_services_post_proto_depIdxs,
		MessageInfos:      file_services_post_proto_msgTypes,
	}.Build()
	File_services_post_proto = out.File
	file_services_post_proto_goTypes = nil
	file_services_post_proto_depIdxs = nil
}
