port: 8091

log:
  logPath: ./logs
  logName: app-server

mysql:
  user: <db_user>
  password: <db_password>
  address: 127.0.0.1:3306
  name: app_db

qiniu:
  accessKey: <qiniu_ak>
  secretKey: <qiniu_sk>
  bucket: <qiniu_bucket>
  domain: <bucket_domain>

baidusms:
  apiKey: <baidu_sms_ak>
  secretKey: <baidu_sms_sk>

im:
  appKey: <juggleim_appkey>
  appSecret: <juggleim_secret>
  apiUrl: https://api.juggleim.com
